### ISSUE TITLE
Where to Enter the credentials

### ISSUE THREAD

**Issue by Mohammedgadi123** [mapbox/cloudfront-log-reader#22]
I have created a demo.js file and copied below lines in it,on executing it by writing command in command prompt `node demo.js` it gives me error below.

**demo.js**
```
var reader = require('cloudfront-log-reader');
var logStream = reader.LogStream('s3://mybucket/cf-logs/');
logStream.pipe(process.stdout);
```

**Command:**
_C:\Users\MGadi\Source\Repos>node demo.js

**Error:**
C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

TimeoutError: Missing credentials in config
    at Response.<anonymous> (C:\Users\MGadi\node_modules\s3scan\lib\keys.js:49:4
7)
    at Request.<anonymous> (C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:3
55:18)
    at Request.callListeners (C:\Users\MGadi\node_modules\aws-sdk\lib\sequential
_executor.js:105:20)
    at Request.emit (C:\Users\MGadi\node_modules\aws-sdk\lib\sequential_executor
.js:77:10)
    at Request.emit (C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:615:14)
    at Request.transition (C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:22
:10)
    at AcceptorStateMachine.runTo (C:\Users\MGadi\node_modules\aws-sdk\lib\state
_machine.js:14:12)
    at C:\Users\MGadi\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:3
8:9)
    at Request.<anonymous> (C:\Users\MGadi\node_modules\aws-sdk\lib\request.js:6
17:12)_

**Comment by emilymcafee** [comment]
👋  @Mohammedgadi123 this project uses the javascript aws-sdk - you should be able to [configure your credentials](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) in a number of different ways. One straightforward way is via the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

I'll add a note to readme with ^ as well.

**Comment by Mohammedgadi123** [comment]
can you please tell me where I can find AWS.config in aws-sdk folder??
